//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PGPkeys.rc
//
#define IDS_GENERAL                     1
#define IDS_PASSPHRASEMISMATCH          2
#define IDS_CAPTION                     3
#define IDC_YESTOALL                    3
#define IDS_CAPTIONKEYGEN               4
#define IDS_BADPASSPHRASE               5
#define IDS_INVALIDNUMBITS              6
#define IDS_SUCCESSKEYGEN               7
#define IDS_DEFAULTUID                  8
#define IDS_GROUPIMPORTCAPTION          9
#define IDS_EXPORTCAPTION               10
#define IDS_DELCONFCAPTION              11
#define IDS_DELCONFPRIVKEY              12
#define IDS_DELCONFPUBKEY               13
#define IDS_DELCONFKEY                  13
#define IDS_DELCONFUSERID               14
#define IDS_DELCONFCERT                 15
#define IDS_MEMALLOCFAIL                16
#define IDS_KEYRINGFILTER               17
#define IDS_PRIVKEYCAPTION              18
#define IDS_PUBKEYCAPTION               19
#define IDS_PROPCAPTION                 20
#define IDS_KEYCOLTITLE                 21
#define IDS_VALCOLTITLE                 22
#define IDS_TRUSTCOLTITLE               23
#define IDS_DATECOLTITLE                24
#define IDS_BITSCOLTITLE                25
#define IDS_VERSION                     26
#define IDS_PGPKEYSVERSION              26
#define IDS_BACKUPCAPTION               27
#define IDS_BACKUPDEFAULTFILE           28
#define IDS_BACKUPDEFAULTDIR            29
#define IDS_REGISTRYKEY                 30
#define IDS_CERTMESSAGE                 31
#define IDS_OUTOFMEMORY                 32
#define IDS_GENERICERROR                33
#define IDS_CAPTIONERROR                34
#define IDS_CONFIRMSETDEFAULT           35
#define IDS_VALIDITY0                   36
#define IDS_VALIDITY1                   37
#define IDS_VALIDITY2                   38
#define IDS_VALIDITY3                   39
#define IDS_WRONGPASSPHRASE             40
#define IDS_DELCONFDEFKEY               41
#define IDS_KEYGENPHASE1                42
#define IDS_KEYGENPHASE2                43
#define IDS_DROPFILENAME                44
#define IDS_NODEFAULTKEY                45
#define IDS_CERTKEYNOTONRING            46
#define IDS_NOIMPORTKEYS                47
#define IDS_NOIMPORTKEYSPASTE           48
#define IDS_CANNOTOPENRINGS             49
#define IDS_DELONLYUSERID               50
#define IDS_BACKUPERROR                 51
#define IDS_IMPORTEDSECRETKEYS          52
#define IDS_TRUST0                      54
#define IDS_TRUST1                      55
#define IDS_TRUST2                      56
#define IDS_TRUST3                      57
#define IDS_TRUST4                      58
#define IDS_TRUST5                      59
#define IDS_DEFKEYPASSPHRASE            60
#define IDS_SIGNKEYPASSPHRASE           60
#define IDS_SELKEYPASSPHRASE            61
#define IDS_IMPORTFILTER                63
#define IDS_GROUPIMPORTFILTER           63
#define IDS_COLLAPSEALL                 64
#define IDS_EXPANDALL                   65
#define IDS_COLLAPSESEL                 66
#define IDS_EXPANDSEL                   67
#define IDS_HELPFILENAME                68
#define IDS_PROPTITLE0                  69
#define IDS_RSA                         70
#define IDS_DSA_ELGAMAL                 71
#define IDS_UNKNOWN                     72
#define IDS_NEVER                       73
#define IDS_KEYGENERATION               74
#define IDS_SUBKEYGENERATION            75
#define IDS_MULTCERTMESSAGE2            76
#define IDS_MULTCERTMESSAGE1            77
#define IDS_NODRAGTEXTKEYS              78
#define IDS_SETKEYAXIOMATIC             79
#define IDS_DEFKEYRINGEXTENSION         80
#define IDS_DEFEXPORTEXTENSION          81
#define IDS_CORRUPTKEYRING              84
#define IDS_PGPMAILKEY                  85
#define IDS_ERRONEOUSADK                86
#define IDS_NOSPLASHSWITCH              87
#define IDS_NOUSERNAME                  88
#define IDS_REVOKECONFIRM               89
#define IDS_TRUSTONINVALIDKEY           90
#define IDS_CERTIFYERROR                91
#define IDS_NONSTANDARDNAME             92
#define IDS_REVCONFDEFKEY               93
#define IDS_UNAVAILABLECERT             94
#define IDS_NOUSERADDR                  95
#define IDS_LOCKEDKEYRING               97
#define IDS_EMPTY                       99
#define IDD_PUBMAIL                     102
#define IDD_KEYMAN                      102
#define IDR_MENUCONTEXT                 103
#define IDR_MENUPRIVKEY                 103
#define IDR_MENUKEY                     103
#define IDR_MENUPUBKEY                  104
#define IDB_RSAPRIVKEY                  104
#define IDB_RSASEC                      104
#define IDB_CERT                        105
#define IDR_MENUUID                     105
#define IDR_MENUCERT                    106
#define IDB_RSAPRIVKEYMSK               106
#define IDB_RSASECMSK                   106
#define IDB_CERTMSK                     107
#define IDB_RSAPUBKEY                   108
#define IDB_RSAPUB                      108
#define IDB_RSAPUBKEYMSK                109
#define IDB_RSAPUBMSK                   109
#define IDB_UID                         110
#define IDB_UIDMSK                      111
#define IDR_MENUKEYMAN                  112
#define IDR_MENUDISKEY                  113
#define IDD_PROP1                       114
#define IDR_MENUREVKEY                  114
#define IDD_PROP0                       115
#define IDR_MENUNONE                    115
#define IDD_KEYPROP                     116
#define IDR_MENUEXPKEY                  116
#define IDB_RSADISKEY                   117
#define IDB_RSAPUBDIS                   117
#define IDB_RSADISKEYMSK                118
#define IDB_RSAPUBDISMSK                118
#define IDB_RSAREVKEY                   119
#define IDB_RSAPUBREV                   119
#define IDB_RSAREVKEYMSK                120
#define IDB_RSAPUBREVMSK                120
#define IDB_RSAEXPKEY                   121
#define IDB_RSAPUBEXP                   121
#define IDB_RSAEXPKEYMSK                122
#define IDB_RSAPUBEXPMSK                122
#define IDB_REVCERT                     123
#define IDB_REVCERTMSK                  124
#define IDD_CHANGEPHRASE                125
#define IDD_BACKUPWARN                  126
#define IDD_BADPHRASE                   127
#define IDR_KEYMANACCEL                 128
#define IDD_PASSPHRASE                  129
#define IDD_KEYRAND                     130
#define IDI_EXEICON                     133
#define IDI_ICON1                       134
#define IDC_ICON1                       134
#define IDD_WORKING                     134
#define IDI_ICON2                       135
#define IDC_ICON2                       135
#define IDI_ICON3                       136
#define IDC_ICON3                       136
#define IDI_ICON4                       137
#define IDC_ICON4                       137
#define IDD_KEYGEN                      138
#define IDI_ICON5                       138
#define IDC_ICON5                       138
#define IDI_ICON6                       139
#define IDC_ICON6                       139
#define IDD_LOADING                     139
#define IDI_ICON7                       140
#define IDC_ICON7                       140
#define IDI_ICON8                       141
#define IDC_ICON8                       141
#define IDB_BITMAP6                     142
#define IDB_BADCERTMSK                  143
#define IDD_NEWUSERID                   144
#define IDB_BADCERT                     144
#define IDD_DELETEALL                   145
#define IDB_DSAPUBKEY                   146
#define IDB_DSAPUB                      146
#define IDB_DSAPUBKEYMSK                147
#define IDB_DSAPUBMSK                   147
#define IDB_DSAPRIVKEYMSK               148
#define IDB_DSASECMSK                   148
#define IDB_DSAPRIVKEY                  149
#define IDB_DSASEC                      149
#define IDB_LOGO                        154
#define IDB_LOGOMSK                     155
#define IDR_CLOCKAVI                    162
#define IDB_DSADISKEY                   164
#define IDB_DSAPUBDIS                   164
#define IDB_DSADISKEYMSK                165
#define IDB_DSAPUBDISMSK                165
#define IDB_DSAREVKEY                   166
#define IDB_DSAPUBREV                   166
#define IDB_DSAREVKEYMSK                167
#define IDB_DSAPUBREVMSK                167
#define IDB_DSASECDIS                   168
#define IDB_DSASECDISMSK                169
#define IDB_RSASECDIS                   170
#define IDB_RSASECDISMSK                171
#define IDB_RSASECREV                   172
#define IDB_RSASECREVMSK                173
#define IDB_RSASECEXP                   174
#define IDB_RSASECEXPMSK                175
#define IDB_DSASECEXP                   176
#define IDB_DSASECEXPMSK                177
#define IDB_DSASECREV                   178
#define IDB_DSASECREVMSK                179
#define IDB_DSAPUBEXP                   180
#define IDB_DSAPUBEXPMSK                181
#define IDD_KEYPROPADK                  182
#define IDD_READONLY                    183
#define IDB_RSAUID                      184
#define IDD_SIGNCONFIRM                 184
#define IDB_DSAUID                      185
#define IDD_KEYWIZ_SIGN_OLD             186
#define IDC_CHECK_SIGN_KEY              187
#define IDB_KEYWIZ8                     187
#define IDB_KEYWIZ4                     188
#define IDB_KEYWIZ1                     189
#define IDR_MENUPROMISCUOUS             190
#define IDB_UNCHECK                     192
#define IDB_UNCHECKMSK                  193
#define IDB_CHECK                       194
#define IDB_CHECKMSK                    195
#define IDB_PUSHMSK                     196
#define IDB_PUSH                        197
#define IDB_PUSHED                      198
#define IDB_PUSHEDMSK                   199
#define IDD_KEYWIZ_BADPHRASE            200
#define IDD_KEYWIZ_ADK                  201
#define IDD_KEYWIZ_CORPCERT             202
#define IDR_MENUKEYSEARCH               203
#define IDR_MENUKEYSEARCHSERVER         203
#define IDR_MENUKEYSEARCHLOCAL          204
#define IDB_IMAGES4BIT                  207
#define IDB_IMAGES24BIT                 208
#define IDD_NEWGROUP                    209
#define IDR_MENUGROUP                   213
#define IDR_MENUGROUPKEY                214
#define IDI_OPENLOCK                    220
#define IDI_CLOSEDLOCK                  221
#define IDB_TOOLBAR4BIT                 223
#define IDB_TOOLBAR24BIT                224
#define IDD_KEYWIZ_REVOKER              225
#define IDR_DIALOGACCEL                 226
#define IDI_CLOSELOCK                   228
#define IDD_KEYWIZ_CERTREQ              229
#define IDC_TREELIST                    401
#define IDC_TREELISTGROUP               402
#define IDC_TEXT                        1000
#define IDC_NAME                        1000
#define IDC_RANDOMTEXT                  1000
#define IDC_NUMBER                      1001
#define IDC_SETPRIVATEKEYRING           1001
#define IDC_SETPUBLICKEYRING            1002
#define IDC_PGPBITSIZE                  1003
#define IDC_PRIVATEKEYRING              1005
#define IDC_PUBLICKEYRING               1006
#define IDC_KEYTYPECOMBO                1006
#define IDC_KEYSIZECOMBO                1007
#define IDC_KSCOMBO                     1007
#define IDC_NEVEREXPIRES                1008
#define IDC_EXPIRES                     1009
#define IDC_EXPIRESDAYS                 1010
#define IDC_FINGERPRINT                 1013
#define IDC_TRUSTSLIDER                 1014
#define IDC_VALIDITYBAR                 1015
#define IDC_BITSPROGBAR                 1015
#define IDC_ENABLED                     1016
#define IDC_CHANGEPHRASE                1017
#define IDC_USERID                      1017
#define IDC_KEYID                       1018
#define IDC_PHRASE1                     1018
#define IDC_NEWUSERNAME                 1018
#define IDC_NEWGROUPNAME                1018
#define IDC_CERTDEPTH                   1019
#define IDC_PHRASE2                     1019
#define IDC_KEYTYPE                     1019
#define IDC_CREATEDATE                  1020
#define IDC_USERADDR                    1020
#define IDC_OLDPHRASE                   1021
#define IDC_VALIDITY                    1021
#define IDC_HIDETYPING                  1022
#define IDC_TRUST                       1022
#define IDC_ENCRYPTTOSELF               1023
#define IDC_ADKAGENT                    1023
#define IDC_COMPRESS                    1024
#define IDC_NUMCOMPLETE                 1025
#define IDC_NUMMARGINAL                 1026
#define IDC_NEWPHRASE                   1027
#define IDC_NEWPHRASE1                  1027
#define IDC_NEWPHRASE2                  1028
#define IDC_PHRASE                      1029
#define IDC_BITSREMAIN                  1031
#define IDC_PHASE                       1032
#define IDC_KEYSTRING                   1034
#define IDC_PROMPTSTRING                1035
#define IDC_PASSPHRASE                  1037
#define IDC_STRING                      1037
#define IDC_PASSPHRASE2                 1038
#define IDC_BACKUPNOW                   1038
#define IDC_USEBADPHRASE                1039
#define IDC_EXPIREDATE                  1040
#define IDC_AXIOMATIC                   1041
#define IDC_WORKINGAVI                  1043
#define IDC_NEWEMAILADDR                1045
#define IDC_NEWGROUPDESC                1045
#define IDC_WARNNOMORE                  1046
#define IDC_STATIC_KMI                  1050
#define IDC_PROGRESS_TEXT               1051
#define IDC_STATIC_KMI2                 1052
#define IDC_CHECK_NO_SEND               1053
#define IDC_SENDSIG                     1054
#define IDC_CHECK_SEND                  1055
#define IDC_DUMMYSTOP                   1055
#define IDC_STATIC_KS_TEXT              1056
#define IDC_FREEWARETEXT                1056
#define IDC_NORSAGENTEXT                1056
#define IDC_STATIC_SMALL_GUIDE          1057
#define IDC_STOP                        1057
#define IDC_WIZBITMAP                   1058
#define IDC_EXPIREDAY                   1059
#define IDC_EXPIREMONTH                 1060
#define IDC_EXPIREYEAR                  1061
#define IDC_BADLENGTH                   1062
#define IDC_BADQUALITY                  1063
#define IDC_BADCONFIRM                  1064
#define IDC_ADK                         1066
#define IDC_CORPCERTKEY                 1067
#define IDC_REJECTTEXT                  1068
#define IDC_SERVERLIST                  1070
#define IDC_PROGRESSTEXT                1071
#define IDC_PHRASEQUALITY               1072
#define IDC_MINPHRASEQUALITY            1073
#define IDC_DONTBACKUP                  1078
#define IDC_PENDING                     1079
#define IDC_PHRASELENGTHTEXT            1082
#define IDC_BADQUALITY1                 1085
#define IDC_BADQUALITY2                 1086
#define IDC_BOX1                        1087
#define IDC_BOX2                        1088
#define IDC_MINQUALITYTEXT              1090
#define IDC_REGISTRATION                1091
#define IDC_EXPIRATIONDATE              1092
#define IDC_REVOCATIONKEY               1099
#define IDS_KW_INVALID_KEY_SIZE         1100
#define IDC_STATIC1                     1100
#define IDS_KW_INVALID_KEY_SIZE_TITLE   1101
#define IDS_KW_TITLE                    1101
#define IDC_STATIC2                     1101
#define IDS_KW_INVALID_KEY_TYPE         1102
#define IDC_PRZ                         1102
#define IDC_RADIO_ELGAMALSE             1102
#define IDS_KW_INVALID_KEY_TYPE_TITLE   1103
#define IDS_KW_INVALID_EXPIRATION       1104
#define IDS_KW_INVALID_EXPIRATION_TITLE 1105
#define IDS_KW_MISMATCHED_PHRASES       1106
#define IDS_KW_MISMATCHED_PHRASES_TITLE 1107
#define IDS_KW_ERROR_TITLE              1108
#define IDS_KW_NO_EMAIL                 1109
#define IDS_KW_NO_FULL_NAME             1110
#define IDS_KW_NEED_MORE_BITS           1111
#define IDB_KEYWIZ24                    1112
#define IDS_KW_CONFIRM_TITLE            1112
#define IDD_KEYWIZ_ABOUT                1113
#define IDS_KW_CONFIRM_CANCEL           1113
#define IDD_KEYWIZ_INTRO                1113
#define IDD_KEYWIZ_NAME                 1114
#define IDS_KW_COMPLETE                 1114
#define IDD_KEYWIZ_TYPE                 1115
#define IDS_SETASDEFAULT                1115
#define IDD_KEYWIZ_SIZE                 1116
#define IDS_SETASPRIMARY                1116
#define IDD_KEYWIZ_EXPIRATION           1117
#define IDS_EXPORTFILTER                1117
#define IDD_KEYWIZ_PASSPHRASE           1118
#define IDD_KEYWIZ_RANDOBITS            1119
#define IDD_KEYWIZ_GENERATION           1120
#define IDD_KEYWIZ_DONE                 1121
#define IDD_KEYWIZ_SEND                 1122
#define IDC_PROGRESS                    1123
#define IDC_WIZIMAGE                    1124
#define IDC_FULL_NAME                   1125
#define IDC_RADIO_ELGAMAL               1126
#define IDC_EMAIL                       1127
#define IDC_RADIO_RSA                   1128
#define IDC_RADIO_768                   1129
#define IDC_RADIO_1024                  1130
#define IDC_RADIO_1536                  1131
#define IDC_EDIT_PASSPHRASE2            1132
#define IDC_RADIO_2048                  1133
#define IDC_CHECK_HIDE_TYPING           1134
#define IDC_RADIO_3072                  1135
#define IDC_STATIC_PROGRESS_TEXT        1136
#define IDC_RADIO_PRESET                1136
#define IDC_RADIO_CUSTOM                1137
#define IDC_BUTTON_BACKUP               1138
#define IDC_CUSTOM_BITS                 1139
#define IDC_STATIC_CUSTOM_SIZE          1140
#define IDC_RADIO_CUSTOM_DAYS           1141
#define IDC_EDIT_CUSTOM_DAYS            1142
#define IDC_RADIO_NEVER                 1143
#define IDC_STATIC_DAYS                 1144
#define IDC_EDIT_PASSPHRASE             1145
#define IDS_KW_BAD_PASSPHRASE           1146
#define IDS_KW_BAD_PASSPHRASE_TITLE     1147
#define IDD_KEYWIZ_PRESEND              1148
#define IDS_KW_CANCELING                1149
#define IDS_KW_DSACUSTOM                1150
#define IDS_KW_DSA1536                  1151
#define IDS_KW_DSA2048                  1152
#define IDS_KW_DSA3072                  1153
#define IDS_KW_RSACUSTOM                1154
#define IDS_KW_RSA1536                  1155
#define IDS_KW_RSA2048                  1156
#define IDS_ANIMATIONFILE               1157
#define IDS_KW_CANCELED                 1158
#define IDS_KW_SENDLATER                1159
#define IDS_PUBBACKUPDEFAULTFILE        1160
#define IDS_DEFPUBKEYRINGEXTENSION      1161
#define IDS_PUBBACKUPCAPTION            1162
#define IDS_PUBBACKUPFILTER             1163
#define IDS_BACKUPFILTER                1164
#define IDS_INVALIDDATE                 1165
#define IDS_GROUPCOLTITLE               1166
#define IDS_DESCCOLTITLE                1167
#define IDS_SEARCHTITLE                 1168
#define IDC_RADIO_RSA_V4                1169
#define IDS_KEYSELECTED                 1195
#define IDS_GROUPSELECTED               1196
#define IDS_MULTISELECTED               1198
#define IDS_SERVERSEARCHFAIL            1218
#define IDS_SEARCH_STRINGTABLE_BASE     2000
#define IDS_ATTRIBUTE_1                 2001
#define IDS_ATTRIBUTE_2                 2002
#define IDS_ATTRIBUTE_3                 2003
#define IDS_ATTRIBUTE_4                 2004
#define IDS_ATTRIBUTE_5                 2005
#define IDS_ATTRIBUTE_6                 2006
#define IDS_ATTRIBUTE_7                 2007
#define IDS_ATTRIBUTE_LAST              2008
#define IDS_VERBS_ATTRIBUTE_1           2011
#define IDS_VERBS_ATTRIBUTE_2           2012
#define IDS_VERBS_ATTRIBUTE_3           2013
#define IDS_VERBS_ATTRIBUTE_4           2014
#define IDS_VERBS_ATTRIBUTE_5           2015
#define IDS_VERBS_ATTRIBUTE_6           2016
#define IDS_VERBS_ATTRIBUTE_7           2017
#define IDS_VERBS_LAST                  2018
#define IDS_SPECIFIERS_ATTRIBUTE_1      2021
#define IDS_SPECIFIERS_ATTRIBUTE_2      2022
#define IDS_SPECIFIERS_ATTRIBUTE_3      2023
#define IDS_SPECIFIERS_ATTRIBUTE_4      2024
#define IDS_SPECIFIERS_ATTRIBUTE_5      2025
#define IDS_SPECIFIERS_ATTRIBUTE_6      2026
#define IDS_SPECIFIERS_ATTRIBUTE_7      2027
#define IDS_SPECIFIERS_LAST             2028
#define IDS_LOCAL_KEYRING               2030
#define IDS_CURRENT_SEARCH              2031
#define IDS_DEFAULT_PATH                2032
#define IDS_MONTH1                      2040
#define IDS_MONTH2                      2041
#define IDS_MONTH3                      2042
#define IDS_MONTH4                      2043
#define IDS_MONTH5                      2044
#define IDS_MONTH6                      2045
#define IDS_MONTH7                      2046
#define IDS_MONTH8                      2047
#define IDS_MONTH9                      2048
#define IDS_MONTH10                     2049
#define IDS_MONTH11                     2050
#define IDS_MONTH12                     2051
#define IDS_SEARCH_MESSAGE_BASE         2060
#define IDS_SEARCH_MESSAGE_CONNECT      2061
#define IDS_SEARCH_MESSAGE_CONNECTING   2061
#define IDS_SEARCH_MESSAGE_WAIT         2062
#define IDS_SEARCH_MESSAGE_QUERYING     2062
#define IDS_SEARCH_MESSAGE_RECV         2063
#define IDS_SEARCH_MESSAGE_PROCESSING   2063
#define IDS_SEARCH_MESSAGE_SEND         2064
#define IDS_SEARCH_MESSAGE_SENDING      2064
#define IDS_SEARCH_MESSAGE_COMPLETED    2065
#define IDS_SEARCH_MESSAGE_CLOSING      2065
#define IDS_MONTHS                      2066
#define IDS_BADPHRASELENGTH             2067
#define IDS_REQPHRASELENGTH             2067
#define IDS_BADPHRASEQUALITY            2068
#define IDS_REQPHRASEQUALITY            2068
#define IDS_ADMINPREFSCORRUPT           2069
#define IDS_SUGPHRASELENGTH             2070
#define IDS_SUGPHRASEQUALITY            2071
#define IDS_PHRASEREJECTED              2072
#define IDS_PHRASEWARNED                2073
#define IDS_MISSINGCORPKEY              2074
#define IDS_MISSINGADK                  2075
#define IDS_KW_UNABLETOCOMPLETE         2076
#define IDS_CLIENTPREFSFILE             2077
#define IDS_KSSENDDONE                  2077
#define IDS_MISSINGREVOKERKEY           2077
#define IDS_SENDTOSERVERMENU            2078
#define IDS_SEARCH_MESSAGE_SERVER_NAME  2079
#define IDS_SMALLKEYWARNING             2080
#define IDS_SEARCH_MESSAGE_CANCEL       2081
#define IDS_SEARCHABORTED               2082
#define IDS_KSKEYCOUNT                  2083
#define IDS_PHRASELENGTHTEXT            2084
#define IDS_MISSINGKEYRINGS             2085
#define IDS_SYNCINGKEYSETS              2085
#define IDS_GROUPNAMEFIELD              2086
#define IDS_VALIDITYFIELD               2087
#define IDS_DESCRIPTIONFIELD            2088
#define IDS_NEEDGROUPNAME               2089
#define IDS_UNAVAILABLE                 2090
#define IDS_DELCONFGROUP                2091
#define IDS_NOIMPORTGROUPS              2092
#define IDS_GROUPPROPS                  2093
#define IDS_STRING2094                  2094
#define IDS_NOPASTEKEYS                 2095
#define IDS_EMPTYGROUP                  2096
#define IDS_KSTOOMANYKEYCOUNT           2097
#define IDS_REGISTERURL                 2098
#define IDS_REGISTERURLCGI              2099
#define IDS_EXPIREDADK                  2100
#define IDB_BACKGRND                    2101
#define IDD_SEARCH                      2101
#define IDS_REVOKEDADK                  2101
#define IDB_LARGE_BUTTON1               2102
#define IDS_EXPIREDCORPKEY              2102
#define IDB_LARGE_BUTTON2               2103
#define IDD_CHOICE                      2103
#define IDS_REVOKEDCORPKEY              2103
#define IDB_LARGE_BUTTON3               2104
#define IDS_GROUPSINFREEWARE            2104
#define IDB_MIDDLE_BUTTON3              2105
#define IDS_SEARCHINFREEWARE            2105
#define IDB_MIDDLE_BUTTON2              2106
#define IDS_UPGRADE                     2106
#define IDB_MIDDLE_BUTTON1              2107
#define IDS_UPGRADEURL                  2107
#define IDB_SMALL_BUTTON3               2108
#define IDS_SPLITKEYWARNING             2108
#define IDB_SMALL_BUTTON2               2109
#define IDS_AUTOUPDATEKEYS              2109
#define IDB_SMALL_BUTTON1               2110
#define IDS_AUTOUPDATEINTRODUCERS       2110
#define IDS_TOOLTIPNEWKEY               2111
#define IDS_TOOLTIPREVOKE               2112
#define IDS_TOOLTIPSIGN                 2113
#define IDS_TOOLTIPDELETE               2114
#define IDS_TOOLTIPSEARCH               2115
#define IDS_TOOLTIPNEWGROUP             2116
#define IDS_TOOLTIPUPDATE               2117
#define IDS_TOOLTIPSENDTOSERVER         2118
#define IDS_TOOLTIPPROPERTIES           2119
#define IDS_TOOLTIPIMPORT               2120
#define IDS_TOOLTIPEXPORT               2121
#define IDS_EXPIREDREVOKERKEY           2122
#define IDS_REVOKEDREVOKERKEY           2123
#define IDS_COMCTLERRORSWITCH           2124
#define IDS_DOMAINSERVER                2125
#define IDS_CONNECTIONNOTAUTHENTICATED  2126
#define IDS_NOCONNECTIONYET             2127
#define IDS_SEARCH_MESSAGE_DELETING     2128
#define IDS_SEARCH_MESSAGE_DISABLING    2129
#define IDS_SDKEXPIRED                  2130
#define IDS_NONEWTRUSTEDINTROS          2131
#define IDS_NOUPDATEDKEYS               2132
#define IDS_AUTOUPDATECAPTION           2133
#define IDS_SEARCH_MESSAGE_RECEIVING    2134
#define IDS_NONEWCRLS                   2135
#define IDS_KW_NEED_EMAIL               2136
#define IDS_CUSTOM                      2137
#define IDS_ELGAMAL                     2138
#define IDC_SEARCH                      3000
#define IDC_CLEAR                       3001
#define IDC_LOCATION                    3002
#define IDC_MORE                        3003
#define IDC_FEWER                       3004
#define IDC_ATTRIBUTE                   3005
#define IDC_VERB                        3006
#define IDC_SPECIFIER_COMBO             3007
#define IDC_DEFAULT_GROUP               3008
#define IDC_SPECIFIER_EDIT              3012
#define IDC_SPECIFIER_COMBO_LIST        3013
#define IDC_MONTH                       3016
#define IDC_DAY                         3017
#define IDC_YEAR                        3019
#define IDC_DEFAULT_SPIN                3020
#define IDC_SPIN                        3020
#define IDC_CHOICE_SPIN                 3024
#define IDM_DELETEKEY                   40006
#define IDM_CERTIFYKEY                  40008
#define IDM_REVOKEKEY                   40010
#define IDM_HELPCONTENTS                40013
#define IDM_HELPSEARCH                  40014
#define IDM_HELPTOPICS                  40014
#define IDM_HELPTUTORIAL                40015
#define IDM_HELPABOUT                   40016
#define IDM_NEWKEYPAIR                  40018
#define IDM_DISABLEKEY                  40019
#define IDM_ENABLEKEY                   40020
#define IDM_PROPERTIES                  40021
#define IDM_COLLAPSEALL                 40023
#define IDM_COLLAPSESEL                 40023
#define IDM_EXPANDALL                   40024
#define IDM_EXPANDSEL                   40024
#define IDM_ADDUSERID                   40025
#define IDM_IMPORTKEYS                  40027
#define IDM_EXPORTKEYS                  40028
#define IDM_SELECTALL                   40030
#define IDM_CUTKEY                      40031
#define IDM_COPYKEY                     40032
#define IDM_PASTEKEY                    40033
#define IDM_UNDO                        40034
#define IDM_FILEEXIT                    40038
#define IDM_REVOKECERT                  40039
#define IDM_CREATEKEY                   40041
#define IDM_SETASDEFAULT                40042
#define IDM_ADVERTISE1                  40043
#define IDM_VIEWGROUPS                  40045
#define IDM_SEARCH                      40046
#define IDM_NEWGROUP                    40047
#define IDM_SELECTCOLUMNS               40048
#define IDM_ADDTOMAIN                   40049
#define IDM_SENDTOSERVER                40050
#define IDM_GETFROMSERVER               40051
#define IDM_SENDTOSERVERPOPUP           40052
#define IDM_DELETESERVER                40053
#define IDM_DISABLESERVER               40054
#define IDM_DISABLE                     40055
#define IDM_GROUPPROPS                  40056
#define IDM_GROUPPROPERTIES             40056
#define IDM_FINDKEY                     40059
#define IDM_IMPORTGROUPS                40061
#define IDM_VIEWVALIDITY                40063
#define IDM_VIEWSIZE                    40064
#define IDM_VIEWDESC                    40065
#define IDM_VIEWKEYID                   40066
#define IDM_VIEWTRUST                   40067
#define IDM_VIEWCREATION                40068
#define IDM_VIEWEXPIRATION              40069
#define IDM_VIEWADK                     40070
#define IDM_VIEWTOOLBAR                 40071
#define IDM_REVERIFY                    40072
#define IDM_SPLITKEY                    40073
#define IDM_SENDSHARES                  40074
#define IDM_UPDATEINTRODUCERS           40075
#define IDM_ADDPHOTOID                  40076
#define IDM_UPDATEGROUP                 40079
#define IDM_UPDATEGROUPLISTS            40079
#define IDM_SENDGROUPLISTS              40080
#define IDM_ADDREVOKER                  40081
#define IDM_DOMAINKEYSERVER             40082
#define IDM_PREFERENCES                 40083
#define IDM_ADDCERTIFICATE              40084
#define IDM_RETRIEVECERTIFICATE         40085
#define IDM_UPDATEREVOCATIONS           40086
#define IDM_VIEWKEYID64                 40087

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         40087
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
