//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PGPcl.rc
//
#define IDS_GENERAL                     1
#define IDS_PRIVKEYRINGFILTER           2
#define IDS_PRIVKEYCAPTION              3
#define IDS_PUBKEYCAPTION               4
#define IDS_PROPCAPTION                 5
#define IDS_CAPTIONERROR                6
#define IDS_HELPFILENAME                7
#define IDS_TITLE0                      8
#define IDS_PREF_GENERAL                8
#define IDS_TITLE1                      9
#define IDS_PREF_FILES                  9
#define IDS_TITLE2                      10
#define IDS_PREF_EMAIL                  10
#define IDS_TITLE3                      11
#define IDS_PREF_SERVER                 11
#define IDS_TITLE4                      12
#define IDS_PREF_CA                     12
#define IDS_NOSIGNKEY                   13
#define IDS_RANDOMPROMPT                14
#define IDS_RANDOMDONE                  15
#define IDS_RSA                         16
#define IDS_DH                          17
#define IDS_UNKNOWN                     18
#define IDS_CAPTION                     19
#define IDS_INVALIDWRAP                 20
#define IDS_INVALIDCACHEVALUE           21
#define IDS_PUBKEYRINGFILTER            22
#define IDS_DEFPRIVRINGEXT              23
#define IDS_DEFPUBRINGEXT               24
#define IDS_ILLEGALFILENAME             25
#define IDS_BROWSERERROR                26
#define IDS_RSADSAMIXWARNING            27
#define IDS_ERR_EXPIRED                 28
#define IDS_DOMAIN                      29
#define IDS_LISTED                      30
#define IDS_DELKSPROMPT                 31
#define IDS_SERVEREXISTS                32
#define IDS_NOSERVERNAME                33
#define IDS_INFOTEXT                    34
#define IDS_CREDITTEXT                  35
#define IDS_WEBLINK                     36
#define IDS_NODOMAINNAME                37
#define IDS_SEEDFILEFILTER              38
#define IDS_SEEDFILECAPTION             39
#define IDS_DEFSEEDFILEEXT              40
#define IDS_CAST                        41
#define IDS_3DES                        42
#define IDS_IDEA                        43
#define IDS_NOADMINFILE                 44
#define IDS_CLIENTPREFSFILE             45
#define IDS_ADMINPREFSFILE              46
#define IDS_CONNECTING                  47
#define IDS_WAITING                     48
#define IDS_QUERYING                    48
#define IDS_PROCESSING                  49
#define IDS_SENDING                     50
#define IDS_EXCHANGING                  50
#define IDS_REGISTRYKEY                 51
#define IDS_NOSERVERS                   52
#define IDS_SENDSERVEROK                53
#define IDS_SERVEROK                    53
#define IDS_SENDSERVERERROR             54
#define IDS_SERVERERROR                 54
#define IDS_LOOKINGFORSERVER            55
#define IDS_ERRORPREFIX                 56
#define IDS_ERRORMESSAGECAPTION         57
#define IDS_ERRORMESSAGE                58
#define IDS_DELETING                    59
#define IDS_DISABLING                   60
#define IDS_CLOSING                     61
#define IDS_ERR_OUTOFMEMORY             101
#define IDD_KEYPROPGENERAL              101
#define IDS_ERR_WRONGKEYPASSPHRASE      102
#define IDD_CHANGEPHRASE                102
#define IDS_ERR_INVALIDFILEOPERROR      103
#define IDS_ERR_CATCHALL                104
#define IDS_ERR_KEYIOWRITING            105
#define IDS_ERR_NOFILE                  106
#define IDS_ERR_RNGNOTSEEDED            107
#define IDS_ERR_INPUTFILENOTEXIST       108
#define IDD_KEYRAND                     108
#define IDS_ERR_CANNOTUSEUNTRUSTEDKEY   109
#define IDD_NEWUSERID                   109
#define IDS_ERR_OUTPUTBUFFERTOOSMALL    110
#define IDD_DELETEALL                   110
#define IDS_ERR_KEYRINGCORRUPT          111
#define IDD_KEYPROPADK                  111
#define IDS_ERR_EXTRACTKEYNOTEXIST      112
#define IDD_SIGNCONFIRM                 112
#define IDS_ERR_SIGONLYKEY              113
#define IDD_QUERYADD                    113
#define IDS_ERR_ENCRYPTONLYKEY          114
#define IDD_REVOKECERT                  114
#define IDS_ERR_CORRUPTPACKET           115
#define IDS_ERR_DETSIGFOUND             116
#define IDD_EXPORTPRIVKEY               116
#define IDD_EXPORTDLGEXTENSIONS         116
#define IDS_ERR_NOSECRETKEYS            117
#define IDD_PREF0                       117
#define IDD_PREF_GENERAL                117
#define IDS_ERR_DUPLICATEUSERID         118
#define IDD_PREF1                       118
#define IDD_PREF_FILES                  118
#define IDS_ERR_DUPLICATECERT           119
#define IDD_PREF2                       119
#define IDD_PREF_EMAIL                  119
#define IDS_ERR_FILEPERMISSIONS         120
#define IDD_PREF4                       120
#define IDD_PREF_CA                     120
#define IDS_PHRASEMISMATCH              121
#define IDD_PREF3                       121
#define IDD_PREF_SERVER                 121
#define IDS_EMPTYPHRASE                 122
#define IDD_HELPABOUT                   122
#define IDS_SENDSERVERABORT             123
#define IDD_SPLASH                      123
#define IDS_SERVERABORT                 123
#define IDS_SEARCHABORT                 124
#define IDD_NAG                         124
#define IDS_SEARCHOK                    125
#define IDD_NEWSERVER                   125
#define IDS_SEARCHERROR                 126
#define IDD_SERVERPROGRESS              126
#define IDS_WRONGPHRASE                 127
#define IDS_PHRASEPROMPT                128
#define IDS_DELETESERVEROK              129
#define IDS_DELETESERVERABORT           130
#define IDS_DELETESERVERERROR           131
#define IDS_DISABLESERVEROK             132
#define IDS_DISABLESERVERABORT          133
#define IDS_DISABLESERVERERROR          134
#define IDS_UNKNOWNKEYS                 135
#define IDS_NEEDALGORITHM               136
#define IDS_DSS                         137
#define IDS_ERR_KEYFAILEDPOLICY         138
#define IDS_ERR_INCOMPATIBLESDKAPI      139
#define IDS_GROUPFILENAME               140
#define IDS_EDITSERVERTITLE             141
#define IDS_ERR_UNSUPPORTEDHTTPFILTER   142
#define IDS_ERR_NOSIGNINGKEYFORSEARCH   143
#define IDS_FOUNDMATCHFORPHRASE         144
#define IDS_PGP                         145
#define IDS_BADDECRYPTPHRASE            146
#define IDS_WRONGDECRYPTPHRASE          147
#define IDS_BETATIMEOUT                 148
#define IDS_EVALTIMEOUT                 149
#define IDS_VALIDITYFIELD               150
#define IDS_DESCRIPTIONFIELD            151
#define IDS_PASSPHRASEMISMATCH          201
#define IDB_IMAGES4BIT                  201
#define IDS_CAPTIONKEYGEN               202
#define IDB_IMAGES24BIT                 202
#define IDS_IMPORTCAPTION               203
#define IDB_IMAGES4                     203
#define IDS_EXPORTCAPTION               204
#define IDB_IMAGES24                    204
#define IDS_DELCONFCAPTION              205
#define IDB_CREDITS4                    205
#define IDS_DELCONFPRIVKEY              206
#define IDB_CREDITS1                    206
#define IDB_CREDITS8                    207
#define IDS_DELCONFKEY                  208
#define IDB_SPLASH1                     208
#define IDS_DELCONFUSERID               209
#define IDB_SPLASH4                     209
#define IDS_DELCONFCERT                 210
#define IDB_SPLASH8                     210
#define IDS_KEYRINGFILTER               211
#define IDB_NAG1                        211
#define IDB_NAG4                        212
#define IDS_NAMEFIELD                   213
#define IDB_NAG8                        213
#define IDS_TRUSTFIELD                  215
#define IDS_CREATIONFIELD               216
#define IDS_SIZEFIELD                   217
#define IDD_SENDSHARES                  219
#define IDS_VALIDITY0                   220
#define IDS_VALIDITY1                   221
#define IDS_VALIDITY2                   222
#define IDS_VALIDITY3                   223
#define IDS_DELCONFDEFKEY               224
#define IDS_DROPFILENAME                225
#define IDS_CERTKEYNOTONRING            226
#define IDS_NOIMPORTKEYS                227
#define IDS_NOIMPORTKEYSPASTE           228
#define IDS_DELONLYUSERID               229
#define IDS_IMPORTEDSECRETKEYS          230
#define IDS_TRUST2                      231
#define IDS_TRUST3                      232
#define IDS_TRUST4                      233
#define IDS_TRUST5                      234
#define IDS_SIGNKEYPASSPHRASE           235
#define IDS_SELKEYPASSPHRASE            236
#define IDS_IMPORTFILTER                237
#define IDS_PROPTITLE0                  238
#define IDS_DSA_ELGAMAL                 239
#define IDS_NEVER                       241
#define IDS_NODRAGTEXTKEYS              242
#define IDS_DEFEXPORTEXTENSION          243
#define IDS_ERRONEOUSADK                244
#define IDS_NOUSERNAME                  245
#define IDS_REVOKECONFIRM               246
#define IDS_TRUSTONINVALIDKEY           247
#define IDS_CERTIFYERROR                248
#define IDS_REVCONFDEFKEY               249
#define IDS_UNAVAILABLECERT             250
#define IDS_NOUSERADDR                  251
#define IDS_EXPORTFILTER                252
#define IDS_INVALIDDATE                 253
#define IDS_USERID                      254
#define IDS_FINGERPRINT                 255
#define IDS_KEYIDFIELD                  257
#define IDS_EXPIRATIONFIELD             258
#define IDS_ADKFIELD                    259
#define IDS_RSAPUBKEY                   260
#define IDS_RSASECKEY                   261
#define IDS_RSAPUBEXPKEY                262
#define IDS_RSAPUBREVKEY                263
#define IDS_RSAPUBDISKEY                264
#define IDS_RSASECDISKEY                265
#define IDS_RSASECEXPKEY                266
#define IDS_RSASECREVKEY                267
#define IDS_DSAPUBKEY                   268
#define IDS_DSASECKEY                   269
#define IDS_DSAPUBEXPKEY                270
#define IDS_DSAPUBREVKEY                271
#define IDS_DSAPUBDISKEY                272
#define IDS_DSASECDISKEY                273
#define IDS_DSASECEXPKEY                274
#define IDS_DSASECREVKEY                275
#define IDS_RSAUSERID                   276
#define IDS_DSAUSERID                   277
#define IDS_CERT                        278
#define IDS_REVCERT                     279
#define IDS_BADCERT                     280
#define IDS_KEYSELECTED                 281
#define IDS_UIDSELECTED                 282
#define IDS_CERTSELECTED                283
#define IDS_MULTISELECTED               284
#define IDS_UPLOADOK                    285
#define IDS_REQMINPHRASELEN             286
#define IDS_SUGMINPHRASELEN             287
#define IDS_REQMINPHRASEQUAL            288
#define IDS_SUGMINPHRASEQUAL            289
#define IDS_QUERYCONTINUESIGNING        290
#define IDS_QUERYCONTINUEREVOKINGKEY    291
#define IDS_QUERYCONTINUEREVOKINGCERT   292
#define IDS_QUERYCONTINUEADDINGNAME     293
#define IDS_QUERYCONTINUEADDING         293
#define IDS_DELETEFROMSERVEROK          294
#define IDS_DISABLEONSERVEROK           295
#define IDS_EXPORTCERT                  296
#define IDS_METACERT                    297
#define IDS_EXPORTMETACERT              298
#define IDS_SERVERSEARCHFAIL            299
#define IDS_UNKNOWNADK                  300
#define IDS_UNKNOWNADKID                301
#define IDI_KEYICON                     301
#define IDS_KEYALREADYONSERVER          302
#define IDR_MENUIMPORT                  302
#define IDS_KEYSALREADYONSERVER         303
#define IDR_MENUEDITSERVER              303
#define IDS_PROPTITLE1                  304
#define IDS_PROPTITLE2                  305
#define IDS_VALIDFROM                   306
#define IDS_EXPIRES                     307
#define IDS_SIZE                        308
#define IDS_BADSUBKEYSIZE               309
#define IDS_DELETESUBKEYCONF            310
#define IDS_UNKNOWNKEY                  311
#define IDS_SUBKEYOVERLAP               312
#define IDS_SHARES                      313
#define IDS_SAVESHARES                  314
#define IDS_SHAREPHRASEPROMPT           315
#define IDS_SPLITKEYTITLE               316
#define IDS_SPLITKEYPHRASEPROMPT        317
#define IDS_DEFSHAREEXTENSION           318
#define IDS_DEFSHARENAME                319
#define IDS_PHOTOIDPHRASE               320
#define IDS_PHOTOUSERID                 321
#define IDS_UNKNOWNUSERID               322
#define IDS_UNKNOWNFORMAT               322
#define IDS_UNKNOWNIMAGEFORMAT          325
#define IDS_ERR_IMAGETOOBIG             326
#define IDS_ERR_INVALIDIMAGE            327
#define IDS_REVOKESUBKEYCONF            328
#define IDS_REMOVESUBKEYCONF            329
#define IDS_REMOVEONLYSUBKEYCONF        330
#define IDS_NUMSHARES                   331
#define IDS_ONESHARE                    332
#define IDD_KEYPROPSUBKEYS              401
#define IDD_NEWSUBKEY                   403
#define IDB_QUESTIONMARK                406
#define IDB_REVOKED                     407
#define IDD_SPLITKEY                    408
#define IDD_ADDSHAREHOLDER              409
#define IDR_MENUPHOTOID                 410
#define IDD_CONFIRMAUTHENTICATION       411
#define IDD_SPLITKEYPROGRESS            412
#define IDD_RECONSTITUTEKEY             413
#define IDD_REVERIFYING                 414
#define IDD_WARNINGDLG                  415
#define IDD_NEWPHOTOID                  416
#define IDR_MENUNEWPHOTOID              417
#define IDB_EXPIRED                     418
#define IDB_NOTAVAILABLE                419
#define IDD_DRIVERWARNING               420
#define IDD_KEYPROPREVOKERS             421
#define IDD_SUBKEYGENPROG               422
#define IDD_PGPCERTPROP                 423
#define IDD_X509CERTPROP                424
#define IDD_PREF5                       425
#define IDD_PREF_ADVANCED               425
#define IDD_SELECTX509CERT              426
#define IDD_PREF_HOTKEYS                428
#define IDD_AVLIST                      429
#define IDD_AVPAIR                      430
#define IDR_MENUAVLIST                  432
#define IDC_TREELIST                    1000
#define IDC_YESTOALL                    1001
#define IDC_NAME                        1002
#define IDC_SETPRIVATEKEYRING           1003
#define IDC_SETPUBLICKEYRING            1004
#define IDC_PRIVATEKEYRING              1005
#define IDC_PUBLICKEYRING               1006
#define IDC_NEVEREXPIRES                1007
#define IDC_FINGERPRINT                 1008
#define IDC_TRUSTSLIDER                 1009
#define IDC_VALIDITYBAR                 1010
#define IDC_BITSPROGBAR                 1011
#define IDC_ENABLED                     1012
#define IDC_CHANGEPHRASE                1013
#define IDC_KEYID                       1014
#define IDC_NEWUSERNAME                 1015
#define IDC_PHRASE2                     1016
#define IDC_KEYTYPE                     1017
#define IDC_CREATEDATE                  1018
#define IDC_OLDPHRASE                   1019
#define IDC_HIDETYPING                  1021
#define IDC_ENCRYPTTOSELF               1023
#define IDC_KEYSIZE                     1025
#define IDC_NEWPHRASE1                  1026
#define IDC_NEWPHRASE2                  1027
#define IDC_PHRASE                      1028
#define IDC_PROMPTSTRING                1029
#define IDC_STRING                      1030
#define IDC_EXPIREDATE                  1031
#define IDC_AXIOMATIC                   1032
#define IDC_CIPHER                      1033
#define IDC_NEWEMAILADDR                1034
#define IDC_HASH                        1034
#define IDC_SENDSIG                     1035
#define IDC_SELECTALL                   1036
#define IDC_UNSELECTALL                 1037
#define IDC_KEYLIST                     1038
#define IDC_LOCKCIPHER                  1039
#define IDC_LOCKCIPHER_TEXT             1040
#define IDC_PHRASEQUALITY               1045
#define IDC_MINPHRASEQUALITY            1046
#define IDC_NONEXPORTABLE               1047
#define IDC_EXPORTABLE                  1048
#define IDC_TRUSTED                     1049
#define IDC_META                        1050
#define IDC_MORECHOICES                 1051
#define IDC_FEWERCHOICES                1052
#define IDC_EXPORTABLECHECK             1053
#define IDC_SIGTYPE                     1054
#define IDC_ADVANCEDTEXT1               1055
#define IDC_CHANGEKEYPREF               1055
#define IDC_ADVANCEDTEXT2               1056
#define IDC_ADVANCEDTEXT3               1057
#define IDC_ADVANCEDTEXT4               1058
#define IDC_MINQUALITYTEXT              1059
#define IDC_TRUSTTEXT2                  1060
#define IDC_TRUSTTEXT1                  1061
#define IDC_EXPORTPRIVATEKEYS           1062
#define IDC_EXPIRATION                  1063
#define IDC_EXPIRATIONDATE              1064
#define IDC_PROGRESS                    1066
#define IDC_SHAREFILE                   1093
#define IDC_NUMSHARES                   1094
#define IDC_REMOTECOMPUTER              1095
#define IDC_NETSTATUS                   1096
#define IDC_AUTHENTICATION              1097
#define IDC_SENDSHARES                  1098
#define IDC_WWWLINK                     1100
#define IDC_USEFASTKEYGEN               1102
#define IDC_RNGSEEDFILE                 1103
#define IDC_SETRNGSEEDFILE              1104
#define IDC_ENCRYPTPGPMIME              1105
#define IDC_USEPGPMIME                  1105
#define IDC_DECRYPTCACHEENABLE          1107
#define IDC_WRAPENABLE                  1108
#define IDC_WRAPNUMBER                  1109
#define IDC_SIGNCACHEENABLE             1110
#define IDC_CREDITS                     1111
#define IDC_ENCRYPTBYDEFAULT            1112
#define IDC_SIGNBYDEFAULT               1113
#define IDC_SIGNKEYCOMBO                1114
#define IDC_ASCIIARMOR                  1115
#define IDC_DETACHEDSIG                 1116
#define IDC_BEGIN                       1117
#define IDC_STATIC1                     1118
#define IDC_STATIC2                     1119
#define IDC_STATIC3                     1120
#define IDC_TEXTPROMPT                  1121
#define IDC_REMOVEKEYSERVER             1122
#define IDC_SYNCONUNKNOWN               1123
#define IDC_SYNCONADDNAME               1124
#define IDC_SYNCONKEYSIGN               1125
#define IDC_SYNCONREVOKE                1126
#define IDC_MARGVALIDISINVALID          1127
#define IDC_PREFERREDALG                1128
#define IDC_SETDEFAULTKEYSERVER         1129
#define IDC_EDITKEYSERVER               1129
#define IDC_DOMAINNAME                  1130
#define IDC_PROTOCOL                    1130
#define IDC_SERVERNAME                  1131
#define IDC_ENABLECAST                  1132
#define IDC_ENABLE3DES                  1133
#define IDC_ENABLEIDEA                  1134
#define IDC_DISPMARGVALIDITY            1135
#define IDC_COMMENTBLOCK                1136
#define IDC_KEYLISTBOX                  1137
#define IDC_PROGRESSTEXT                1138
#define IDC_NEWKEYSERVER                1139
#define IDC_WIPECONFIRM                 1140
#define IDC_LDAP                        1141
#define IDC_LDAPS                       1142
#define IDC_HTTP                        1143
#define IDC_CANNOTDECRYPTTEXT           1143
#define IDC_AUTODECRYPT                 1144
#define IDC_WARNONADK                   1145
#define IDC_PHRASECONV                  1146
#define IDC_SYNCONSTATICTEXT            1147
#define IDC_BUYNOW                      1148
#define IDC_DECRYPTCACHETIME            1149
#define IDC_SIGNCACHETIME               1150
#define IDC_ALGALLOWED                  1151
#define IDC_ALGDISABLED                 1152
#define IDC_ALGALLOW                    1153
#define IDC_ALGDISABLE                  1154
#define IDC_ALGMOVEUP                   1155
#define IDC_ALGMOVEDOWN                 1156
#define IDC_CHANGESUBKEYPASS            1180
#define IDC_SUBKEYLIST                  1201
#define IDC_NEWSUBKEY                   1202
#define IDC_REVOKESUBKEY                1203
#define IDC_REMOVESUBKEY                1204
#define IDC_ADKLIST                     1205
#define IDC_STARTDATE                   1207
#define IDC_SUBKEYSIZE                  1208
#define IDC_SUBKEYTYPE                  1209
#define IDC_EXPIRESON                   1211
#define IDC_ONEPASSWIPE                 1212
#define IDC_MULTIPASSWIPE               1213
#define IDC_OVERWRITEPATTERN            1214
#define IDC_NUMPASSESTEXT               1216
#define IDC_OVERWRITETEXT               1217
#define IDC_NUMPASSES                   1218
#define IDC_NUMPASSESSPIN               1219
#define IDC_SERVERKEY                   1220
#define IDC_SECUREADD                   1221
#define IDC_SECUREDELETE                1222
#define IDC_LIST                        1223
#define IDC_LISTED                      1223
#define IDC_PHOTOID                     1225
#define IDC_KEYTOSPLIT                  1227
#define IDC_SHAREHOLDERS                1228
#define IDC_CURRENTSHAREHOLDER          1229
#define IDC_REMOVESHAREHOLDER           1230
#define IDC_ADDSHAREHOLDER              1231
#define IDC_THRESHOLD                   1232
#define IDC_TOTALSHARES                 1233
#define IDC_SHARES                      1234
#define IDC_SHARESSPIN                  1235
#define IDC_THRESHOLDSPIN               1237
#define IDC_NEWSHAREHOLDER              1238
#define IDC_KEYNAME                     1240
#define IDC_VALIDITY                    1242
#define IDC_PROGRESSBAR                 1243
#define IDC_STARTNETWORK                1245
#define IDC_NETWORK                     1245
#define IDC_SHARESCOLLECTED             1247
#define IDC_SHARESNEEDED                1248
#define IDC_NETWORKINSTRUCTIONS         1249
#define IDC_WARNCHECK                   1250
#define IDC_STATUS                      1251
#define IDC_WARNINGTEXT                 1251
#define IDC_STATUSTEXT                  1252
#define IDC_AUTHENTICATIONTEXT          1253
#define IDC_TEXT                        1254
#define IDC_PORT                        1256
#define IDC_ANYDOMAIN                   1257
#define IDC_SPECIFIEDDOMAIN             1258
#define IDC_DOMAIN                      1259
#define IDC_SELECTFILE                  1263
#define IDC_PHOTOSCROLLBAR              1264
#define IDC_SYNCONVERIFY                1265
#define IDC_SETASROOT                   1268
#define IDC_IMPORTKEY                   1269
#define IDC_AUTHTEXT                    1270
#define IDC_FRAME                       1271
#define IDC_PROMPT                      1272
#define IDC_NOMOREWARNINGS              1273
#define IDC_KEYTORECON                  1274
#define IDC_STARTDATETEXT               1275
#define IDC_SUBKEYAVI                   1276
#define IDC_STATICTEXT1                 1277
#define IDC_STATICTEXT2                 1278
#define IDC_DOMAINTEXT                  1280
#define IDC_EXPORTCOMPATIBLE            1281
#define IDC_EXPORTCOMPLETE              1282
#define IDC_INCLUDEEXTENSIONS           1283
#define IDC_EXPIRES                     1284
#define IDC_STATIC4                     1285
#define IDC_STATIC7                     1288
#define IDC_CREATIONDATE                1291
#define IDC_SHOWSIGNER                  1293
#define IDC_CHECK1                      1296
#define IDC_USESECUREVIEWER             1296
#define IDC_ENABLEPURGECACHE            1296
#define IDC_ENABLETWOFISH               1296
#define IDC_USEHEXFINGERPRINT           1296
#define IDC_APPENDKEYIDENABLE           1296
#define IDC_CHECK2                      1297
#define IDC_EXPIRED                     1297
#define IDC_ENABLEENCRYPT               1297
#define IDC_APPENDKEYFPENABLE           1297
#define IDC_BLOCK_ADK                   1297
#define IDC_NUKENONPGPBLOCKS            1297
#define IDC_CHECK3                      1298
#define IDC_REVOKED                     1298
#define IDC_ENABLESIGN                  1298
#define IDC_KEYID64                     1298
#define IDC_ICONFRAME                   1299
#define IDC_ISSUER                      1300
#define IDC_NEXTCRL                     1301
#define IDC_LASTCRL                     1302
#define IDC_CERTIFICATE                 1303
#define IDC_SIGNATURE                   1304
#define IDC_ROOTCERT                    1304
#define IDC_EXCHANGE                    1305
#define IDC_CLEARCERT                   1305
#define IDC_SETCERT                     1306
#define IDC_URL                         1307
#define IDC_REVURL                      1308
#define IDC_TYPE                        1309
#define IDC_X509CERTLIST                1310
#define IDC_SELECTPROMPT                1311
#define IDC_PURGEHOTKEY                 1312
#define IDC_ENCRYPTHOTKEY               1313
#define IDC_ENABLEENCRYPTSIGN           1314
#define IDC_ENABLEDECRYPT               1315
#define IDC_SIGNHOTKEY                  1316
#define IDC_ENCRYPTSIGNHOTKEY           1317
#define IDC_DECRYPTHOTKEY               1318
#define IDC_MOVEUP                      1319
#define IDC_MOVEDOWN                    1320
#define IDC_AVLIST                      1321
#define IDC_NEWAV                       1322
#define IDC_REMOVEAV                    1323
#define IDC_ATTRIBUTELIST               1327
#define IDC_VALUE                       1328
#define IDC_CATYPE                      1333
#define IDC_EDITAV                      1334
#define IDC_HEXFINGERPRINT              1335
#define IDC_FINGERPRINT1                1337
#define IDC_FINGERPRINT2                1338
#define IDC_FINGERPRINT3                1339
#define IDC_FINGERPRINT4                1340
#define IDC_ENABLEBLOWFISH              1341
#define IDC_COMBO_GO                    1342
#define IDC_ENABLEAES128                1342
#define IDC_VSCOMBO                     1343
#define IDC_ENABLEAES192                1343
#define IDC_PREFKEYRINGBACKUP           1344
#define IDC_ENABLEAES256                1344
#define IDC_PREFERREDHASHALG            1345
#define IDC_LONGDATE                    1346
#define IDC_VBSCOMBO                    1347
#define IDC_VBLOCKSTRING                1348
#define IDL_ENABLED                     1349
#define IDL_DISABLED                    1350
#define IDC_BTN_ENABLE                  1351
#define IDC_BTN_DISABLE                 1352
#define IDC_BTN_MOVEUP                  1353
#define IDC_BTN_MOVEDOWN                1354
#define IDC_PREFERREDHASHALGRSA3        1355
#define IDC_PREFERREDHASHALGRSA4        1356
#define IDC_PREFERREDHASHALGELG         1357
#define IDS_SHAREFILEFILTER             2109
#define IDS_SHAREFILECAPTION            2110
#define IDS_STATUSNOTCONNECTED          2111
#define IDS_STATUSCONNECTING            2112
#define IDS_STATUSCONNECTED             2113
#define IDS_STATUSSENDING               2114
#define IDS_STATUSCLOSING               2115
#define IDS_SENDAUTHPROMPT              2116
#define IDS_DECRYPTSHARESPROMPT         2117
#define IDS_STATUSAUTHENTICATED         2118
#define IDS_SPLITKEYCONFIRMATION        2119
#define IDS_SENDSUCCESS                 2120
#define IDS_CREATINGSHARES              2121
#define IDS_SAVINGSHARES                2122
#define IDS_SPLITTINGKEY                2123
#define IDS_SPLITKEYGONE                2124
#define IDS_SHAREKEYGONE                2125
#define IDS_RECONKEYTITLE               2126
#define IDS_SHAREKEYMISMATCH            2127
#define IDS_SHARENUMMISMATCH            2128
#define IDS_RSASECSHRKEY                2129
#define IDS_DSASECSHRKEY                2130
#define IDS_ERR_INVALIDCOMMONCONTROLS   2131
#define IDS_STARTNETWORK                2132
#define IDS_STOPNETWORK                 2133
#define IDS_STATUSRECEIVING             2134
#define IDS_RECONAUTHPROMPT             2135
#define IDS_PREPARINGTOVERIFY           2136
#define IDS_VERIFYING                   2137
#define IDS_UNIDENTIFIEDHOST            2138
#define IDS_SERVER                      2139
#define IDS_LDAP                        2140
#define IDS_LDAPS                       2141
#define IDS_HTTP                        2142
#define IDS_BADPASSKEY                  2143
#define IDS_BITMAPDEFEXT                2144
#define IDS_BITMAPFILTER                2145
#define IDS_OPENBITMAPTITLE             2146
#define IDS_EXPCERT                     2147
#define IDS_NEWPHRASEPROMPT             2148
#define IDS_PHRASECHANGED               2149
#define IDS_RECONSTITUTEKEY             2150
#define IDS_KEYRECONSTITUTED            2151
#define IDS_CHANGEPHRASE                2152
#define IDS_DUPLICATESHARES             2153
#define IDS_LICENSEDTO                  2154
#define IDS_VERSION                     2155
#define IDS_NOROOTSERVER                2156
#define IDS_UNEXPECTEDAUTHKEY           2157
#define IDS_INVALIDAUTHKEY              2158
#define IDS_NEWAUTHKEY                  2159
#define IDS_ENFORCEFIELD                2160
#define IDS_IMPORT                      2161
#define IDS_ADDREVOKERPROMPT            2162
#define IDS_QUERYADDPROMPT              2163
#define IDS_ADDEDREVOKERS               2164
#define IDS_ADDREVOKERCONFIRM           2165
#define IDS_NOTENOUGHKEYSTOADDREVOKER   2166
#define IDS_STATUSFINISHED              2167
#define IDS_DONE                        2168
#define IDS_DUPLICATESERVER             2169
#define IDS_IMPORTKEYERROR              2170
#define IDS_PROPTITLE3                  2171
#define IDS_ERRONEOUSREVOKER            2172
#define IDS_VALIDAUTHKEY                2173
#define IDS_ERR_FILEOPFAILED            2174
#define IDS_KEYNOTSIGNEDBYCORP          2175
#define IDS_NOVALIDDEFAULTKEY           2176
#define IDS_NOOUTADK                    2177
#define IDS_NOCORPSIGNKEY               2178
#define IDS_TEXTOUTPUT                  2179
#define IDS_CONVENCRYPTION              2180
#define IDS_WIPEORIGINAL                2181
#define IDS_ATLEASTONEORCONV            2182
#define IDS_DETACHEDSIG                 2183
#define IDS_ANIMATIONFILE               2184
#define IDS_PHOTOIDALREADYEXISTS        2185
#define IDS_ADDEDSENTREVOKERS           2186
#define IDS_ERR_FAILEDSERVERPOLICY      2187
#define IDS_STATUSLISTENING             2187
#define IDS_MUSTHAVEDEFAULTSERVER       2188
#define IDS_SPLITKEYSNOTALLOWED         2189
#define IDS_BADSHAREFILEPASSPHRASE      2190
#define IDS_KEYRINGFOLDER               2191
#define IDS_FYEO                        2192
#define IDS_WIPEWODEFAULT               2193
#define IDS_SDA                         2194
#define IDS_CLIENTREGISTRYKEY           2195
#define IDS_CLIENTPREFSFOLDER           2196
#define IDS_ADMINPREFSFOLDER            2197
#define IDS_CERTPROPSTITLE              2198
#define IDS_NA                          2199
#define IDS_RECEIVING                   2200
#define IDS_NTUSERPROFILE               2201
#define IDS_SDKPREFSFOLDER              2202
#define IDS_SDKPREFSFILE                2203
#define IDS_DEFAULTUSERFOLDER           2204
#define IDS_X509CERT                    2205
#define IDS_X509REVCERT                 2206
#define IDS_X509EXPCERT                 2207
#define IDS_TLS_PGP_DHE_DSS_WITH_CAST_CBC_SHA 2208
#define IDS_TLS_PGP_DHE_RSA_WITH_CAST_CBC_SHA 2209
#define IDS_TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA 2210
#define IDS_TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA 2211
#define IDS_TLS_RSA_WITH_3DES_EDE_CBC_SHA 2212
#define IDS_TLS_RSA_WITH_IDEA_CBC_SHA   2213
#define IDS_TLS_PGP_RSA_WITH_CAST_CBC_SHA 2214
#define IDS_TLS_PGP_DHE_DSS_WITH_NULL_SHA 2215
#define IDS_TLS_DHE_DSS_WITH_NULL_SHA   2216
#define IDS_TLS_NULL_WITH_NULL_NULL     2217
#define IDS_TITLE5                      2218
#define IDS_PREF_ADVANCED               2218
#define IDS_CATYPEPGP                   2219
#define IDS_CATYPENETTOOLS              2220
#define IDS_CATYPEVERISIGN              2221
#define IDS_CATYPEENTRUST               2222
#define IDS_NOX509CERTS                 2223
#define IDS_ROOTCAPROMPT                2224
#define IDS_CERTRETRIEVALFAIL           2225
#define IDS_ERR_NOROOTCACERT            2226
#define IDS_ERR_NOCASERVER              2227
#define IDS_CANTDERIVEATTRIBUTES        2228
#define IDS_CANTDERIVEATTRIBUTESONLY    2229
#define IDS_CERTRETRIEVALSUCCESS        2230
#define IDS_CERTIFICATEREQUESTED        2231
#define IDS_PREF_HOTKEYS                2232
#define IDS_OVERLAPPINGHOTKEYS          2233
#define IDS_HOTKEYINUSE                 2234
#define IDS_PURGEHOTKEYINUSE            2234
#define IDS_ENCRYPTHOTKEYINUSE          2235
#define IDS_SIGNHOTKEYINUSE             2236
#define IDS_ENCRYPTSIGNHOTKEYINUSE      2237
#define IDS_DECRYPTHOTKEYINUSE          2238
#define IDS_ATTRIBUTE                   2239
#define IDS_VALUE                       2240
#define IDS_AVORGNAME                   2241
#define IDS_AVORGUNITNAME               2242
#define IDS_AVCOUNTRY                   2243
#define IDS_AVLOCALITY                  2244
#define IDS_AVSTATE                     2245
#define IDS_AVSTREET                    2246
#define IDS_AVPOSTAL                    2247
#define IDS_AVPOBOX                     2248
#define IDS_AVTELEPHONE                 2249
#define IDS_AVINITIALS                  2250
#define IDS_AVDNSNAME                   2251
#define IDS_AVCOMMONNAME                2252
#define IDS_AVEMAIL                     2253
#define IDS_CATYPEUNSPECIFIED           2254
#define IDS_NEWATTRIBUTETITLE           2255
#define IDS_NOMOREATTRIBUTES            2256
#define IDS_MUSTENTERVALUE              2257
#define IDS_CHALLENGEPROMPT             2258
#define IDS_CHALLENGEWARNING            2259
#define IDS_MISSINGATTRIBUTEVALUE       2260
#define IDS_AVFIRSTNAME                 2261
#define IDS_AVMIDDLENAME                2262
#define IDS_AVLASTNAME                  2263
#define IDS_TWOFISH                     2264
#define IDS_PGPNETSDKPREFSFILE          2265
#define IDS_TRAILINGCASLASH             2266
#define IDS_AVIPADDRESS                 2267
#define IDS_INVALIDIPADDRESS            2268
#define IDS_AVCERTTYPE                  2269
#define IDS_PKCS12PROMPT                2270
#define IDS_CANTREORDERUSERIDS          2271
#define IDS_KEYIDFIELD64                2272
#define IDS_BLOWFISH                    2273
#define IDS_AES128                      2274
#define IDS_AES192                      2275
#define IDS_AES256                      2276
#define IDS_UNKNOWNCIPHER               2277
#define IDS_ELGPUBKEY                   2278
#define IDS_ELGSECKEY                   2279
#define IDS_ELGPUBEXPKEY                2280
#define IDS_ELGPUBREVKEY                2281
#define IDS_ELGPUBDISKEY                2282
#define IDS_ELGSECDISKEY                2283
#define IDS_ELGSECEXPKEY                2284
#define IDS_ELGSECREVKEY                2285
#define IDS_ELGUSERID                   2286
#define IDS_ELGSECSHRKEY                2287
#define IDS_ELGAMAL                     2288
#define IDS_RSAPUBKEYV4                 2289
#define IDS_RSASECKEYV4                 2290
#define IDS_RSAPUBEXPKEYV4              2291
#define IDS_RSAPUBREVKEYV4              2292
#define IDS_RSAPUBDISKEYV4              2293
#define IDS_RSASECDISKEYV4              2294
#define IDS_RSASECEXPKEYV4              2295
#define IDS_RSASECREVKEYV4              2296
#define IDM_EDITSERVER                  40001
#define IDM_KEYPROPERTIES               40002
#define IDM_PASTEBITMAP                 40003
#define IDM_COPYBITMAP                  40004
#define IDM_REMOVESERVER                40005
#define IDM_NEWSERVER                   40006
#define IDM_SETASROOT                   40007
#define IDM_MOVEUP                      40008
#define IDM_MOVEDOWN                    40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        433
#define _APS_NEXT_COMMAND_VALUE         40011
#define _APS_NEXT_CONTROL_VALUE         1358
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
